# Uncomment the next line to define a global platform for your project
platform :ios, '16.3'

target 'pp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pp
  pod 'Kingfisher', '~> 7.10.1'
  pod 'Mantis', '~> 2.20.0'
	pod 'KakaoSDKCommon'   # 필수 요소를 담은 공통 모듈
	pod 'KakaoSDKAuth'     # 사용자 인증
	pod 'KakaoSDKUser'     # 카카오 로그인, 사용자 관리
  pod 'Moya/Combine', '~> 15.0'
  pod 'SwiftyJSON'
end
