# Uncomment the next line to define a global platform for your project
platform :ios, '16.3'

target 'pp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pp
  pod 'Kingfisher', '~> 7.10.1'
  pod 'Mantis', '~> 2.20.0'
end
